spring:
  application:
    name: spring-boot-docker
  main:
    banner-mode: off

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      slo:
        all: 1ms,2ms,5ms,10ms,25ms,50ms,100,250ms,500ms,1s
