server:
  port: 8765

spring:
  security:
    oauth2:
      authorizationserver:
        client:
          example:
            registration:
              client-id: client
              client-secret: "{noop}secret"
              client-authentication-methods: client_secret_basic
              authorization-grant-types: authorization_code,refresh_token,client_credentials
              redirect-uris:
                - http://127.0.0.1:8080/login/oauth2/code/
              scopes: openid,profile
              require-authorization-consent: true

logging:
  level:
    org.springframework.security: debug
