create table message (id bigint generated by default as identity, title varchar(255), author varchar(255), content varchar(255));
insert into message (title, author, content) values ('Hello', 'unmacaque', 'Hello World');
