plugins {
    id 'com.github.node-gradle.node'
}

node {
    download = true
    version = "26.3.0"
    pnpmVersion = "11.6.0"
}

tasks.register('npmRunBuild', NpmTask) {
    args = ['run', 'build']
}

tasks.register('pnpmRunBuild', PnpmTask) {
    args = ['run', 'build']
}

tasks.named('pnpmInstall') {
    environment["CI"] = "true"
}
