create table message (id bigint generated by default as identity, title varchar(255), author varchar(255), content varchar(255), created_date timestamp with time zone, last_modified_date timestamp with time zone);

insert into message ( title, author, content, created_date, last_modified_date ) values ('Hello', 'Flintstone', 'This is the first message posted with this nice litte application. Hope you like it. Feel free to post more messages. 🙂', '2017-04-23 20:46:00.000+02', '2017-04-23 20:46:00.000+02');
insert into message ( title, author, content, created_date, last_modified_date ) values ('Hi John', 'Simpson', 'Hi John. Nice blog you have got there. Will check regularly for some interesting updates. 👋', '2017-04-23 20:46:00.000+02', '2017-04-23 20:46:00.000+02');
