spring:
  ai:
    ollama:
      chat:
        model: granite4.1:3b
      init:
        pull-model-strategy: always
        timeout: 60s
        max-retries: 1
        embedding:
          include: false
    mcp:
      client:
        streamable-http:
          connections:
            server:
              url: http://localhost:8180/mcp

management:
  endpoints:
    web:
      exposure:
        include: "*"
