on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: docker
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"
      - run: ./gradlew check
