spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration
  datasource:
    url: jdbc:hsqldb:mem:spring
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    properties:
      hibernate:
        cache:
          provider_class: org.hibernate.cache.NoCacheProvider
    show-sql: true
