spring:
  security:
    oauth2:
      client:
        provider:
          gitlab:
            issuer-uri: https://gitlab.com
        registration:
          gitlab:
            authorization-grant-type: authorization_code
            client-name: GitLab
            client-id: <placeholder>
            client-secret: <placeholder>
            redirect-uri: "{baseUrl}/login/oauth2/code/"
            scope: openid
