spring:
  security:
    oauth2:
      client:
        provider:
          bitbucket:
            authorization-uri: https://bitbucket.org/site/oauth2/authorize
            token-uri: https://bitbucket.org/site/oauth2/access_token
            user-info-uri: https://api.bitbucket.org/2.0/user
            user-name-attribute: username
          gitlab:
            issuer-uri: https://gitlab.com
        registration:
          gitlab:
            authorization-grant-type: authorization_code
            client-name: GitLab
            client-id: <placeholder>
            client-secret: <placeholder>
            redirect-uri: "{baseUrl}/login/oauth2/code/"
            scope: openid
