server:
  port: 8443
  ssl:
    enabled: true
    bundle: server
    client-auth: need

spring:
  ssl:
    bundle:
      pem:
        server:
          reload-on-update: true
          keystore:
            certificate: "classpath:ssl/server/server.pem"
            private-key: "classpath:ssl/server/server.key"
          truststore:
            certificate: "classpath:ssl/ca/trust.pem"

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    ssl:
      enabled: true
  server:
    port: 8080
    ssl:
      enabled: false
