spring:
  application:
    name: spring-boot-docker

logging:
  structured:
    format:
      console: logstash

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
  metrics:
    distribution:
      slo:
        all: 1ms,2ms,5ms,10ms,25ms,50ms,100,250ms,500ms,1s
