spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration
  datasource:
    url: jdbc:h2:mem:spring
  h2:
    console:
      enabled: true
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    properties:
      hibernate:
        cache:
          provider_class: org.hibernate.cache.NoCacheProvider
    show-sql: true
