spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            #issuer-uri: http://localhost:8180/auth/realms/spring-boot/
            authorization-uri: http://localhost:8180/auth/realms/spring-boot/protocol/openid-connect/auth
            token-uri: http://localhost:8180/auth/realms/spring-boot/protocol/openid-connect/token
            jwk-set-uri: http://localhost:8180/auth/realms/spring-boot/protocol/openid-connect/certs
            user-info-uri: http://localhost:8180/auth/realms/spring-boot/protocol/openid-connect/userinfo
          bitbucket:
            authorization-uri: https://bitbucket.org/site/oauth2/authorize
            token-uri: https://bitbucket.org/site/oauth2/access_token
            user-info-uri: https://api.bitbucket.org/2.0/user
            user-name-attribute: username
          gitlab:
            issuer-uri: https://gitlab.com
        registration:
          keycloak:
            authorization-grant-type: authorization_code
            client-name: Keycloak
            client-id: spring-security-oauth
            client-secret: springboot
            redirect-uri: http://localhost:8080/login/oauth2/code/
            scope: openid
