server:
  port: 8443
  ssl:
    enabled: true
    bundle: server
    client-auth: need

spring:
  ssl:
    bundle:
      pem:
        server:
          keystore:
            certificate: "classpath:ssl/server/server.pem"
            private-key: "classpath:ssl/server/server.key"
          truststore:
            certificate: "classpath:ssl/ca/trust.pem"
