server:
  port: 8443
  ssl:
    enabled: true
    certificate: classpath:ssl/server.pem
    certificate-private-key: classpath:ssl/server.key
    key-password:
    client-auth: need
    trust-certificate: classpath:ssl/trust.pem
