server:
  port: 8443
  ssl:
    enabled: true
    certificate: classpath:ssl/server/server.pem
    certificate-private-key: classpath:ssl/server/server.key
    client-auth: need
    trust-certificate: classpath:ssl/ca/trust.pem
