server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:server.p12
    key-store-password: storepass
    client-auth: need
    trust-store: classpath:trust.p12
    trust-store-password: trustpass
