server:
  port: 8443
  ssl:
    enabled: true
    certificate: classpath:server.pem
    certificate-private-key: classpath:server.key
    key-password:
    client-auth: need
    trust-certificate: classpath:trust.pem
