server:
  port: 8761
spring:
  application:
    name: eureka-server
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
