resilience4j:
  bulkhead:
    instances:
      myBulkhead:
        maxConcurrentCalls: 2
  circuitbreaker:
    instances:
      myBreaker:
        failureRateThreshold: 20
        waitDurationInOpenState: 10s
        slidingWindowSize: 10
  ratelimiter:
    instances:
      myLimiter:
        timeoutDuration: 1s
        limitRefreshPeriod: 10s
        limitForPeriod: 10
  retry:
    instances:
      myRetry:
        maxAttempts: 3
        waitDuration: 50ms
        failAfterMaxAttempts: true
