spring:
  security:
    user:
      name: admin
      password: togglz
      roles: ADMIN,USER
togglz:
  console:
    feature-admin-authority: ROLE_ADMIN
  feature-enums: com.gmail.unmacaque.spring.togglz.Features
