spring:
  security:
    user:
      name: admin
      password: togglz
      roles: ADMIN,USER
  datasource:
    url: jdbc:h2:mem:spring
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
togglz:
  console:
    feature-admin-authority: ROLE_ADMIN
  feature-enums: com.gmail.unmacaque.spring.togglz.Features
