plugins {
    id 'unmacaque.spring-boot'
    id 'unmacaque.protobuf'
}

dependencies {
    implementation project(':projects:grpc:common')
    implementation 'com.google.protobuf:protobuf-java-util'
    implementation 'org.springframework.boot:spring-boot-starter-grpc-client'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    testImplementation 'org.springframework.boot:spring-boot-starter-grpc-client-test'
}

description = 'Spring gRPC Client'
