spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10://spring-data-rest
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
