create table message (id bigint generated by default as identity, title varchar(255), author varchar(255), content varchar(255));

insert into message ( title, author, content ) values ('Hello', 'John Doe', 'This is the first message posted with this nice litte application. Hope you like it. Feel free to post more messages. 🙂');
insert into message ( title, author, content ) values ('Hi John', 'Jane Doe', 'Hi John. Nice blog you have got there. Will check regularly for some interesting updates. 👋');
